### ISSUE TITLE
Cannot instantiate Module

### ISSUE THREAD

**Issue by jpardobl** [maros/Zway-Astronomy#1]
SORRY THIS IS IN THE WRONG PROJECT.
Hello.

When I download development version 1.04 I get the following error when instantiating the module.

[2016-01-06 13:01:14.185] [I] [core] Notification: error (core): Cannot instantiate module: InfluxDbStats: TypeError: undefined is not a function
[2016-01-06 13:01:14.275] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:287:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:504:14)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:656:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:27:11)

To reproduce de error I just:
- Download the last development branch: git clone https://github.com/maros/Zway-InfluxDbStats.git InfluxDbStats
- Reload the server
- Create an app through the web ui
- Read the logs and find the upper stack trace.

Thanks!

**Comment by maros** [comment]
Hi, I'm a little bit confused. In the bug report you are referring to Zway-InfluxDbStats, whereas this is the Zway-Astronomy repo. The stack trace shows  InfluxDbStats but there is no version 1.04 - this only exists for Zway-Astronomy.  

I just assume that you are refering to InfluxDbStats:
- Which zway version are you running (2.2.0 is known to have some issues)
- Did you install BaseModule first?
- Did you instantiate BaseModule?

**Comment by jpardobl** [comment]
I was refering to InfluxDbStats. Sorry for the mistake.
