### ISSUE TITLE
Notification: error (core): Cannot instantiate module: Astronomy: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by constin** [maros/Zway-Astronomy#4]
raspbian, raspberry P3

[2016-09-29 21:35:21.530] [I] [core] --- Starting module Astronomy Module
[2016-09-29 21:35:21.544] [I] [core] Executing script: /\* ...
[2016-09-29 21:35:21.548] [I] [core] Notification: error (core): Cannot instantiate module: Astronomy: TypeError: Cannot read property 'toString' of undefined
[2016-09-29 21:35:21.557] [I] [core] TypeError: Cannot read property 'toString' of undefined
    at Astronomy.init (automation/userModules/Astronomy/index.js:55:42)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:425:22)
    at AutomationController.createInstance (automation/classes/AutomationController.js:857:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1029:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

**Comment by maros** [comment]
Looks like you did not provide a proper location (latitude and longitude). Does this error also occur if you fill out both form fields?

**Comment by maros** [comment]
Closing due to lack of feedback.
